#!/bin/bash
date=$1

year=$(echo "$1" |  awk -F- '{print $1}')
month=$(echo "$1" |  awk -F- '{print $2}')
days="$year""$month"

wget --no-check-certificate "http://www.twse.com.tw/ch/inc/download.php?l1=%A4W%A5%AB%A4%BD%A5q%A4%EB%B3%F8&l2=%A4j%BDL%A1B%A6U%B2%A3%B7%7E%C3%FE%AA%D1%A4%CE%A4W%A5%AB%AA%D1%B2%BC%A5%BB%AFq%A4%F1%A1B%B4%DE%A7Q%B2v%A4%CE%AA%D1%BB%F9%B2b%AD%C8%A4%F1&url=/ch/statistics/download/04/001/""$days""_C04001.zip" -O eps/"$days".zip
unzip  eps/"$days".zip -d ./eps
rm eps/"$days".zip


file=$(find -type f -printf '%T+ %p\n' | sort | head -1 | awk '{print $2}')
echo $file
mv $file eps/"$days".xls
sync
