#!/bin/bash

DES_PATH="$1"

#input $2 format: %Y-%m-%d
#days=$(date --date="yesterday" +"%Y-%m-%d")

year=$(echo "$2" |  awk -F- '{print $1}')
year_c=$[$year-1911]
month=$(echo "$2" |  awk -F- '{print $2}')
day=$(echo "$2" |  awk -F- '{print $3}')

if [[ "$1" == "waitsu" ]]; then
    wget --post-data="download=csv&qdate=$year_c%2F$month%2F$day&sorting=by_issue" http://www.twse.com.tw/ch/trading/fund/TWT38U/TWT38U.php -O $DES_PATH/"$year""$month""$day".csv
elif [[ "$1" == "tsuyinshan" ]]; then
    wget --post-data="download=csv&qdate=$year_c%2F$month%2F$day&sorting=by_issue" http://www.twse.com.tw/ch/trading/fund/TWT43U/TWT43U.php -O $DES_PATH/"$year""$month""$day".csv
elif [[ "$1" == "toshin" ]]; then
    wget --post-data="download=csv&qdate=$year_c%2F$month%2F$day&sorting=by_issue" http://www.twse.com.tw/ch/trading/fund/TWT44U/TWT44U.php -O $DES_PATH/"$year""$month""$day".csv
fi
sleep 0.1

if [[ "$1" == "waitsu" ]]; then
    sed -i 's/*/\ /' $DES_PATH/"$year""$month""$day".csv
elif [[ "$1" == "tsuyinshan" ]]; then
    sed -i 's/=*//' $DES_PATH/"$year""$month""$day".csv
elif [[ "$1" == "toshin" ]]; then
    sed -i 's/*/\ /' $DES_PATH/"$year""$month""$day".csv
fi

iconv -f big5 -t utf-8  $DES_PATH/"$year""$month""$day".csv -o $DES_PATH/"$year""$month""$day".csv
sync
