#!/bin/bash
mode=$1
code=$2

#income 股利
#bonus 營收


if [[ "$1" == "income" ]]; then
    key_num=2
    wget "https://tw.finance.yahoo.com/d/s/earning_"$code".html" -O "$1"/"$code"".html"
elif [[ "$1" == "bonus" ]]; then
    key_num=3
    wget "https://tw.finance.yahoo.com/d/s/dividend_"$code".html" -O "$1"/"$code"".html"
fi

./html2xml "$1"/"$code"".html" "$1"/"$code"".xml"
sync
iconv -f big5 -t utf-8 "$1"/"$code"".xml" -o "$1"/"$code"".xml"
sync
rm "$1"/"$code"".html"
./XML_Parser $key_num "$1"/"$code"".xml" "$1"/"$code"".csv"
sync
rm "$1"/"$code"".xml"
sync
