#!/bin/bash

code=$2

year=$(echo "$1" |  awk -F- '{print $1}')
month=$(echo "$1" |  awk -F- '{print $2}')

days="$year""$month"

wget -O - "http://www.twse.com.tw/ch/trading/exchange/STOCK_DAY/STOCK_DAY_print.php?genpage=genpage/Report"$days"/"$days"_F3_1_8_"$code".php&type=csv" > price/"$code"/"$days"_"$code".csv

sleep 0.2

iconv -f big5 -t utf-8 "price/"$code"/"$days"_"$code".csv" -o "price/"$code"/"$days"_"$code".csv"

#mv /root/"$days.csv" /root/stock_ui/toshin/

